#!/bin/bash

# Flutter Feature Generator
# Usage: bash scripts/generate_feature.sh <feature_name> [--local|--remote|--both]
#
# Flags:
#   --remote  (default) remote datasource only
#   --local             local datasource only (Drift)
#   --both              local + remote datasource
#
# Examples:
#   bash scripts/generate_feature.sh expense --local
#   bash scripts/generate_feature.sh auth --remote
#   bash scripts/generate_feature.sh profile --both
#   bash scripts/generate_feature.sh notification   ← defaults to --remote

# ─────────────────────────────────────────
# SETUP
# ─────────────────────────────────────────

FEATURE=${1}
FLAG=${2:-"--remote"}

if [ -z "$FEATURE" ]; then
  echo "❌ Usage: bash scripts/generate_feature.sh <feature_name> [--local|--remote|--both]"
  exit 1
fi

case $FLAG in
  --local|--remote|--both) ;;
  *)
    echo "❌ Invalid flag: $FLAG"
    echo "   Valid flags: --local, --remote, --both"
    exit 1
    ;;
esac

# Convert snake_case to PascalCase — awk for macOS + Linux compatibility
CLASS=$(echo "$FEATURE" | awk -F_ '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}' OFS='')

# Detect lib root
if [ -d "lib" ]; then
  LIB="lib"
elif [ -d "../lib" ]; then
  LIB="../lib"
else
  echo "❌ Cannot find lib/ directory. Run from Flutter project root."
  exit 1
fi

F="$LIB/features/$FEATURE"

if [ -d "$F" ]; then
  echo "❌ Feature '$FEATURE' already exists at $F"
  echo "   Delete it manually if you want to regenerate."
  exit 1
fi

echo "🚀 Generating feature: $FEATURE (${CLASS}) [$FLAG]"

# ─────────────────────────────────────────
# CREATE DIRECTORIES
# ─────────────────────────────────────────

mkdir -p "$F/domain/entities"
mkdir -p "$F/domain/repositories"
mkdir -p "$F/domain/usecases"
mkdir -p "$F/data/models"
mkdir -p "$F/data/datasources"
mkdir -p "$F/data/repositories"
mkdir -p "$F/presentation/cubit"
mkdir -p "$F/presentation/widgets"

# ─────────────────────────────────────────
# DOMAIN — ENTITY
# ─────────────────────────────────────────

cat > "$F/domain/entities/${FEATURE}_entity.dart" << DARTEOF
import 'package:equatable/equatable.dart';

class ${CLASS} extends Equatable {
  final String id;
  // TODO: add fields

  const ${CLASS}({
    required this.id,
  });

  @override
  List<Object?> get props => [id];
}
DARTEOF

cat > "$F/domain/entities/entities.dart" << DARTEOF
export '${FEATURE}_entity.dart';
DARTEOF

# ─────────────────────────────────────────
# DOMAIN — REPOSITORY INTERFACE
# ─────────────────────────────────────────

cat > "$F/domain/repositories/${FEATURE}_repository.dart" << DARTEOF
import '../entities/entities.dart';

abstract class ${CLASS}Repository {
  Stream<List<${CLASS}>> watchAll();
  Future<void> add(${CLASS} ${FEATURE});
  Future<void> update(${CLASS} ${FEATURE});
  Future<void> delete(String id);
}
DARTEOF

cat > "$F/domain/repositories/repositories.dart" << DARTEOF
export '${FEATURE}_repository.dart';
DARTEOF

# ─────────────────────────────────────────
# DOMAIN — USE CASE
# ─────────────────────────────────────────

cat > "$F/domain/usecases/get_${FEATURE}.dart" << DARTEOF
import '../entities/entities.dart';
import '../repositories/${FEATURE}_repository.dart';

class Get${CLASS}UseCase {
  final ${CLASS}Repository repository;

  const Get${CLASS}UseCase(this.repository);

  Future<void> call() async {
    // TODO: implement
  }
}
DARTEOF

cat > "$F/domain/usecases/usecases.dart" << DARTEOF
export 'get_${FEATURE}.dart';
DARTEOF

cat > "$F/domain/domain.dart" << DARTEOF
export 'entities/entities.dart';
export 'repositories/repositories.dart';
export 'usecases/usecases.dart';
DARTEOF

echo "  ✅ Domain layer"

# ─────────────────────────────────────────
# DATA — MODEL
# ─────────────────────────────────────────

if [ "$FLAG" = "--local" ]; then
  cat > "$F/data/models/${FEATURE}_model.dart" << DARTEOF
import '../../domain/entities/entities.dart';

// Extension on Drift generated class — no manual wrapper needed
// ${CLASS}Data is auto-generated by Drift from table definition
extension ${CLASS}DataMapper on ${CLASS}Data {
  ${CLASS} toEntity() => ${CLASS}(
    id: id,
    // TODO: map fields
  );
}

extension ${CLASS}EntityMapper on ${CLASS} {
  ${CLASS}TableCompanion toCompanion() => ${CLASS}TableCompanion.insert(
    id: id,
    // TODO: map fields
  );
}
DARTEOF

elif [ "$FLAG" = "--remote" ]; then
  cat > "$F/data/models/${FEATURE}_model.dart" << DARTEOF
import '../../domain/entities/entities.dart';

class ${CLASS}Model {
  final String id;
  // TODO: add fields matching API response

  const ${CLASS}Model({
    required this.id,
  });

  factory ${CLASS}Model.fromMap(Map<String, dynamic> map) {
    return ${CLASS}Model(
      id: map['id'] as String,
      // TODO: map fields
    );
  }

  ${CLASS} toEntity() => ${CLASS}(
    id: id,
    // TODO: map fields
  );
}
DARTEOF

elif [ "$FLAG" = "--both" ]; then
  # Local — Drift extension
  cat > "$F/data/models/${FEATURE}_local_model.dart" << DARTEOF
import '../../domain/entities/entities.dart';

// Extension on Drift generated class — no manual wrapper needed
// ${CLASS}Data is auto-generated by Drift from table definition
extension ${CLASS}DataMapper on ${CLASS}Data {
  ${CLASS} toEntity() => ${CLASS}(
    id: id,
    // TODO: map fields
  );
}

extension ${CLASS}EntityMapper on ${CLASS} {
  ${CLASS}TableCompanion toCompanion() => ${CLASS}TableCompanion.insert(
    id: id,
    // TODO: map fields
  );
}
DARTEOF

  # Remote — Model class
  cat > "$F/data/models/${FEATURE}_remote_model.dart" << DARTEOF
import '../../domain/entities/entities.dart';

class ${CLASS}Model {
  final String id;
  // TODO: add fields matching API response

  const ${CLASS}Model({
    required this.id,
  });

  factory ${CLASS}Model.fromMap(Map<String, dynamic> map) {
    return ${CLASS}Model(
      id: map['id'] as String,
      // TODO: map fields
    );
  }

  ${CLASS} toEntity() => ${CLASS}(
    id: id,
    // TODO: map fields
  );
}
DARTEOF
fi

# ─────────────────────────────────────────
# DATA — DATASOURCE ABSTRACT
# ─────────────────────────────────────────

if [ "$FLAG" = "--local" ]; then

  # Local only — no abstract needed, direct impl
  cat > "$F/data/datasources/${FEATURE}_local_datasource.dart" << DARTEOF
import '../../../../core/database/app_database.dart';
import '../models/${FEATURE}_model.dart';
import '../../domain/entities/entities.dart';

class ${CLASS}LocalDataSource {
  final AppDatabase database;

  const ${CLASS}LocalDataSource(this.database);

  Stream<List<${CLASS}>> watchAll() {
    return (database.select(database.${FEATURE}Table))
        .watch()
        .map((rows) => rows.map((r) => r.toEntity()).toList());
  }

  Future<void> insert(${CLASS} ${FEATURE}) {
    return database
        .into(database.${FEATURE}Table)
        .insert(${FEATURE}.toCompanion());
  }

  Future<void> update(${CLASS} ${FEATURE}) {
    return (database.update(database.${FEATURE}Table)
          ..where((t) => t.id.equals(${FEATURE}.id)))
        .write(${FEATURE}.toCompanion());
  }

  Future<void> delete(String id) {
    return (database.delete(database.${FEATURE}Table)
          ..where((t) => t.id.equals(id)))
        .go();
  }
}
DARTEOF

elif [ "$FLAG" = "--remote" ]; then

  # Remote only — no abstract needed, direct impl
  cat > "$F/data/datasources/${FEATURE}_remote_datasource.dart" << DARTEOF
import 'package:dio/dio.dart';
import '../../../../core/network/api_endpoints.dart';
import '../models/${FEATURE}_model.dart';
import '../../domain/entities/entities.dart';

class ${CLASS}RemoteDataSource {
  final Dio client;

  const ${CLASS}RemoteDataSource(this.client);

  Future<List<${CLASS}>> getAll() async {
    // TODO: implement
    // final response = await client.get(ApiEndpoints.${FEATURE}s);
    // return (response.data as List)
    //     .map((json) => (json as Map<String, dynamic>).to${CLASS}Entity())
    //     .toList();
    throw UnimplementedError();
  }

  Future<void> create(${CLASS} ${FEATURE}) async {
    // TODO: implement
    throw UnimplementedError();
  }

  Future<void> update(${CLASS} ${FEATURE}) async {
    // TODO: implement
    throw UnimplementedError();
  }

  Future<void> delete(String id) async {
    // TODO: implement
    throw UnimplementedError();
  }
}
DARTEOF

elif [ "$FLAG" = "--both" ]; then

  # Both — abstract interface + two impls
  cat > "$F/data/datasources/${FEATURE}_datasource.dart" << DARTEOF
import '../../domain/entities/entities.dart';

abstract class ${CLASS}DataSource {
  Future<List<${CLASS}>> getAll();
  Future<void> create(${CLASS} ${FEATURE});
  Future<void> update(${CLASS} ${FEATURE});
  Future<void> delete(String id);
}
DARTEOF

  cat > "$F/data/datasources/${FEATURE}_local_datasource.dart" << DARTEOF
import '../../../../core/database/app_database.dart';
import '${FEATURE}_datasource.dart';
import '../models/${FEATURE}_model.dart';
import '../../domain/entities/entities.dart';

class ${CLASS}LocalDataSource implements ${CLASS}DataSource {
  final AppDatabase database;

  const ${CLASS}LocalDataSource(this.database);

  Stream<List<${CLASS}>> watchAll() {
    return (database.select(database.${FEATURE}Table))
        .watch()
        .map((rows) => rows.map((r) => r.toEntity()).toList());
  }

  @override
  Future<List<${CLASS}>> getAll() async {
    final rows = await database.select(database.${FEATURE}Table).get();
    return rows.map((r) => r.toEntity()).toList();
  }

  @override
  Future<void> create(${CLASS} ${FEATURE}) {
    return database
        .into(database.${FEATURE}Table)
        .insert(${FEATURE}.toCompanion());
  }

  @override
  Future<void> update(${CLASS} ${FEATURE}) {
    return (database.update(database.${FEATURE}Table)
          ..where((t) => t.id.equals(${FEATURE}.id)))
        .write(${FEATURE}.toCompanion());
  }

  @override
  Future<void> delete(String id) {
    return (database.delete(database.${FEATURE}Table)
          ..where((t) => t.id.equals(id)))
        .go();
  }
}
DARTEOF

  cat > "$F/data/datasources/${FEATURE}_remote_datasource.dart" << DARTEOF
import 'package:dio/dio.dart';
import '../../../../core/network/api_endpoints.dart';
import '${FEATURE}_datasource.dart';
import '../models/${FEATURE}_model.dart';
import '../../domain/entities/entities.dart';

class ${CLASS}RemoteDataSource implements ${CLASS}DataSource {
  final Dio client;

  const ${CLASS}RemoteDataSource(this.client);

  @override
  Future<List<${CLASS}>> getAll() async {
    // TODO: implement
    throw UnimplementedError();
  }

  @override
  Future<void> create(${CLASS} ${FEATURE}) async {
    // TODO: implement
    throw UnimplementedError();
  }

  @override
  Future<void> update(${CLASS} ${FEATURE}) async {
    // TODO: implement
    throw UnimplementedError();
  }

  @override
  Future<void> delete(String id) async {
    // TODO: implement
    throw UnimplementedError();
  }
}
DARTEOF

fi

# ─────────────────────────────────────────
# DATA — REPOSITORY IMPL
# ─────────────────────────────────────────

if [ "$FLAG" = "--local" ]; then

  cat > "$F/data/repositories/${FEATURE}_repository_impl.dart" << DARTEOF
import '../../domain/entities/entities.dart';
import '../../domain/repositories/${FEATURE}_repository.dart';
import '../datasources/${FEATURE}_local_datasource.dart';

class ${CLASS}RepositoryImpl implements ${CLASS}Repository {
  final ${CLASS}LocalDataSource localDataSource;

  const ${CLASS}RepositoryImpl({required this.localDataSource});

  @override
  Stream<List<${CLASS}>> watchAll() {
    return localDataSource.watchAll();
  }

  @override
  Future<void> add(${CLASS} ${FEATURE}) => localDataSource.insert(${FEATURE});

  @override
  Future<void> update(${CLASS} ${FEATURE}) => localDataSource.update(${FEATURE});

  @override
  Future<void> delete(String id) => localDataSource.delete(id);
}
DARTEOF

elif [ "$FLAG" = "--remote" ]; then

  cat > "$F/data/repositories/${FEATURE}_repository_impl.dart" << DARTEOF
import '../../domain/entities/entities.dart';
import '../../domain/repositories/${FEATURE}_repository.dart';
import '../datasources/${FEATURE}_remote_datasource.dart';

class ${CLASS}RepositoryImpl implements ${CLASS}Repository {
  final ${CLASS}RemoteDataSource remoteDataSource;

  const ${CLASS}RepositoryImpl({required this.remoteDataSource});

  @override
  Stream<List<${CLASS}>> watchAll() {
    // Remote does not stream — convert to stream
    return Stream.fromFuture(remoteDataSource.getAll());
  }

  @override
  Future<void> add(${CLASS} ${FEATURE}) => remoteDataSource.create(${FEATURE});

  @override
  Future<void> update(${CLASS} ${FEATURE}) => remoteDataSource.update(${FEATURE});

  @override
  Future<void> delete(String id) => remoteDataSource.delete(id);
}
DARTEOF

elif [ "$FLAG" = "--both" ]; then

  cat > "$F/data/repositories/${FEATURE}_repository_impl.dart" << DARTEOF
import '../../domain/entities/entities.dart';
import '../../domain/repositories/${FEATURE}_repository.dart';
import '../datasources/${FEATURE}_local_datasource.dart';
import '../datasources/${FEATURE}_remote_datasource.dart';

// Offline-first: local is source of truth
// Remote syncs in background
class ${CLASS}RepositoryImpl implements ${CLASS}Repository {
  final ${CLASS}LocalDataSource localDataSource;
  final ${CLASS}RemoteDataSource remoteDataSource;

  const ${CLASS}RepositoryImpl({
    required this.localDataSource,
    required this.remoteDataSource,
  });

  @override
  Stream<List<${CLASS}>> watchAll() {
    return localDataSource.watchAll();
  }

  @override
  Future<void> add(${CLASS} ${FEATURE}) async {
    await localDataSource.create(${FEATURE});
    // TODO: sync to remote
  }

  @override
  Future<void> update(${CLASS} ${FEATURE}) async {
    await localDataSource.update(${FEATURE});
    // TODO: sync to remote
  }

  @override
  Future<void> delete(String id) async {
    await localDataSource.delete(id);
    // TODO: sync to remote
  }

  Future<void> syncFromRemote() async {
    // TODO: fetch remote → save local → stream auto emits
  }
}
DARTEOF

fi

echo "  ✅ Data layer [$FLAG]"

# ─────────────────────────────────────────
# PRESENTATION — STATE
# ─────────────────────────────────────────

cat > "$F/presentation/cubit/${FEATURE}_state.dart" << DARTEOF
import 'package:equatable/equatable.dart';
import '../../domain/entities/entities.dart';

sealed class ${CLASS}State extends Equatable {
  const ${CLASS}State();
}

class ${CLASS}Initial extends ${CLASS}State {
  @override
  List<Object?> get props => [];
}

class ${CLASS}Loading extends ${CLASS}State {
  @override
  List<Object?> get props => [];
}

class ${CLASS}Loaded extends ${CLASS}State {
  final List<${CLASS}> items;

  const ${CLASS}Loaded({required this.items});

  @override
  List<Object?> get props => [items];
}

class ${CLASS}Error extends ${CLASS}State {
  final String message;

  const ${CLASS}Error(this.message);

  @override
  List<Object?> get props => [message];
}
DARTEOF

# ─────────────────────────────────────────
# PRESENTATION — CUBIT
# ─────────────────────────────────────────

cat > "$F/presentation/cubit/${FEATURE}_cubit.dart" << DARTEOF
import 'dart:async';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../domain/usecases/get_${FEATURE}.dart';
import '${FEATURE}_state.dart';

class ${CLASS}Cubit extends Cubit<${CLASS}State> {
  final Get${CLASS}UseCase get${CLASS};

  StreamSubscription? _subscription;

  ${CLASS}Cubit({
    required this.get${CLASS},
  }) : super(const ${CLASS}Initial());

  Future<void> load() async {
    emit(const ${CLASS}Loading());
    try {
      await get${CLASS}();
      emit(${CLASS}Loaded(items: const []));
    } catch (e) {
      emit(${CLASS}Error(e.toString()));
    }
  }

  @override
  Future<void> close() {
    _subscription?.cancel();
    return super.close();
  }
}
DARTEOF

cat > "$F/presentation/cubit/cubit.dart" << DARTEOF
export '${FEATURE}_cubit.dart';
export '${FEATURE}_state.dart';
DARTEOF

# ─────────────────────────────────────────
# PRESENTATION — WIDGETS
# ─────────────────────────────────────────

for WIDGET in list_item empty_state; do
  WIDGETCLASS=$(echo "${FEATURE}_${WIDGET}" | awk -F_ '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}' OFS='')
  cat > "$F/presentation/widgets/${WIDGET}_widget.dart" << DARTEOF
import 'package:flutter/material.dart';

class ${WIDGETCLASS}Widget extends StatelessWidget {
  const ${WIDGETCLASS}Widget({super.key});

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
DARTEOF
done

cat > "$F/presentation/widgets/widgets.dart" << DARTEOF
export 'list_item_widget.dart';
export 'empty_state_widget.dart';
DARTEOF

cat > "$F/presentation/presentation.dart" << DARTEOF
export 'cubit/cubit.dart';
export 'widgets/widgets.dart';
DARTEOF

echo "  ✅ Presentation layer"

# ─────────────────────────────────────────
# FEATURE PUBLIC API
# ─────────────────────────────────────────

cat > "$F/${FEATURE}.dart" << DARTEOF
// Public API for ${FEATURE} feature.
// Data layer is intentionally not exported.
export 'domain/domain.dart';
export 'presentation/presentation.dart';
DARTEOF

# ─────────────────────────────────────────
# DONE
# ─────────────────────────────────────────

echo ""
echo "✅ Feature '${FEATURE}' generated at $F"
echo ""
echo "Files created:"
find "$F" -type f | sort | sed "s|$F/||"
echo ""
echo "Next steps:"
echo "  1. Fill TODO fields in domain/entities/${FEATURE}_entity.dart"
if [ "$FLAG" = "--local" ] || [ "$FLAG" = "--both" ]; then
echo "  2. Add ${CLASS}Table to core/database/app_database.dart"
echo "  3. Run: dart run build_runner build --delete-conflicting-outputs"
echo "  4. Register dependencies in core/di/injection_container.dart"
echo "  5. Add route in core/router/app_router.dart"
else
echo "  2. Add endpoint to core/network/api_endpoints.dart"
echo "  3. Register dependencies in core/di/injection_container.dart"
echo "  4. Add route in core/router/app_router.dart"
fi