import '../../../../core/database/app_database.dart';
import '../../domain/entities/entities.dart';

// Extension on Drift generated class — no manual wrapper needed
// ExpenseTableData is auto-generated by Drift from table definition
extension ExpenseDataMapper on ExpenseTableData {
  Expense toEntity() => Expense(
        id: id,
        title: title,
        amount: amount,
        date: date,
        category: category,
        createdAt: createdAt,
      );
}

extension ExpenseEntityMapper on Expense {
  ExpenseTableCompanion toCompanion() => ExpenseTableCompanion.insert(
        id: id,
        title: title,
        amount: amount,
        date: date,
        category: category,
        // createdAt skip — withDefault(currentDateAndTime) handle otomatis
      );
}
